### ISSUE TITLE
could this use ttsc?

### ISSUE THREAD

**Issue by daolou** [a7ul/esbuild-node-tsc#4]
ttsc is [ttypescript](https://github.com/cevek/ttypescript) which provide plugins of typescript

**Comment by a7ul** [comment]
No, this is just a bridge between tsc and esbuild

**Comment by RIP21** [comment]
@daolou to clarify why it won't. It's because `ttsc` is extending `tsc` compilation itself, so it affects files that will be emitted.
This esbuild-node-tsc is IMO a little misleading naming for people that don't understand underlying tooling, but the main takeaway is that this is not using TSC at all (I'm pretty sure you can run it even without `typescript` dependency but with valid `tsconfig.json`) it compiles your TS and JS files using `esbuild` so then you can run it using regular `node ./dir/file.js` .
